DROP TABLE IF EXISTS ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION;
DROP TABLE IF EXISTS ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS;
CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS
(
    ID_TIMESTAMP    DATETIME PRIMARY KEY,
    BOOL            BIT,
    SOME_ENUM       VARCHAR(100),
    BIG_DECIMAL     DECIMAL(38),
    BIG_INTEGER     DECIMAL(20),
    DATE            DATETIME,
    LOCAL_DATE_TIME DATETIME,
    ZONED_DATE_TIME VARCHAR(30)
);
CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION
(
    ID_TIMESTAMP DATETIME NOT NULL PRIMARY KEY,
    DATA         VARCHAR(100),
    ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS TIMESTAMP
);
