DROP TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION;
DROP TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS;

CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS
(
    ID_TIMESTAMP    TIMESTAMP PRIMARY KEY,
    BOOL            BOOLEAN,
    SOME_ENUM       VARCHAR(100),
    BIG_DECIMAL     DECIMAL(65),
    BIG_INTEGER     BIGINT,
    DATE            TIMESTAMP,
    LOCAL_DATE_TIME TIMESTAMP,
    ZONED_DATE_TIME VARCHAR(30)
);
CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION
(
    "ID_TIMESTAMP" TIMESTAMP PRIMARY KEY,
    DATA           VARCHAR(100),
    ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS TIMESTAMP
);
